services:
  postgres:
    image: postgres:16-alpine
    container_name: mynote-postgres
    environment:
      POSTGRES_USER: mynote
      POSTGRES_PASSWORD: mynote123
      POSTGRES_DB: mynotedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
